name = "entry"
framework = "nextjs"
packageManager = "npm"
installCommand = "npm install"
buildCommand = "SKIP_PRODUCTION_MIGRATE_GUARD=1 npm run build && mkdir -p apps/web/.next/standalone/apps/web/.next && cp -r apps/web/.next/static apps/web/.next/standalone/apps/web/.next/static && cp -r apps/web/public apps/web/.next/standalone/apps/web/public"
startCommand = "node apps/web/.next/standalone/apps/web/server.js"
port = 3000
projectId = "proj_ibab5ldta4l63qoentq7"
deploymentId = "dep_u0eek0tcjcogs82yjvy6x"
projectUrl = "https://entry.pxxl.pro"
deploymentUrl = "https://pxxl.app/dashboard/projects/proj_ibab5ldta4l63qoentq7/deployments/dep_u0eek0tcjcogs82yjvy6x"
lastDeployedAt = "2026-07-24T20:16:28.340Z"
