// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/instructions/dynamic.ts";
import * as module_3 from "../../agent/sandbox/sandbox.ts";
import * as module_4 from "../../agent/tools/browser_use.ts";
import * as module_5 from "../../agent/tools/choose.ts";
import * as module_6 from "../../agent/tools/code_artifact.ts";
import * as module_7 from "../../agent/tools/doc_compose.ts";
import * as module_8 from "../../agent/tools/make_it_real.ts";
import * as module_9 from "../../agent/tools/python_coding.ts";
import * as module_10 from "../../agent/tools/task_analysis.ts";
import * as module_11 from "../../agent/tools/web_crawl.ts";
import * as module_12 from "../../agent/tools/web_search.ts";
import * as module_13 from "../../agent/subagents/claude/agent.ts";
import * as module_14 from "../../agent/subagents/gemini/agent.ts";
import * as module_15 from "../../agent/subagents/gpt/agent.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "instructions/dynamic.ts": module_2,
                  "sandbox/sandbox.ts": module_3,
                  "tools/browser_use.ts": module_4,
                  "tools/choose.ts": module_5,
                  "tools/code_artifact.ts": module_6,
                  "tools/doc_compose.ts": module_7,
                  "tools/make_it_real.ts": module_8,
                  "tools/python_coding.ts": module_9,
                  "tools/task_analysis.ts": module_10,
                  "tools/web_crawl.ts": module_11,
                  "tools/web_search.ts": module_12
                })
            }),
      "subagents/claude": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_13
                })
            }),
      "subagents/gemini": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_14
                })
            }),
      "subagents/gpt": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_15
                })
            })
    })
});

export default moduleMap;
