// Generated by eve. Do not edit by hand.
import { POST } from "../../../../../../node_modules/eve/.eve/workflow-cache/28a600623d81/workflows.mjs";

export default async ({ req }) => {
  return await POST(req);
};
